apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-service-app
  namespace: gitops-ftw
spec:
  project: default
  source:
    repoURL: git@github.com:MGTheTrain/helm-chart-samples-ftw.git
    path: ./gitops/helm/sample-service/
    targetRevision: main
    directory:
      recurse: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitops-ftw
  syncPolicy:
    automated:
      prune: true
      selfHeal: true